### PR TITLE
Added Opencv4 support.

### PR DESCRIPTION
**Pull request by jobesu14**
Modified CMaklist to search for OpenCv 4.x. If found -> use it and define "OPENCV4" that will be use as compiler driective in code.

Added compiler directive in code to conditionally support OpenCv 4.x.

### CODE REVIEW

**Comment by slitcch** [comment]
This is a necessary change for getting this working with ubuntu 20.04. On 20.04, this patch gets rid of all the compiler errors relating to openCV 4

**Comment by GSORF** [comment]
Thank you. This patch made ORB-SLAM3 work on ubuntu 20.04. However, files like the Optimizer.cc or Tracking.cc have changed since this pull request. Please rebase your pull request so that it can be added to master.

**Comment by jobesu14** [comment]
Ok, should be good to go.

**Comment by rkent** [comment]
Could you also fix Examples/ROS/ORB_SLAM3/CMakeLists.txt?

**Pull request closed without merging**
